---
# tasks file for uptime
- name: check uptime
  hosts: all
  tasks: 
     - name: check upim 
       command: "uptime"
       register: uptime

     - name: prin result 
       debug:
         msg: : "{{ uptime }}"
